// Added by George Marselis <george@marsel.is>


enum RESNIOS_TIMEOUT {
	// RES_TIMEOUT  = 120,
	NIOS_TIMEOUT = 120
};

enum niosResCmd { 
	NIOS2RES_EOF,
	NIOS2RES_HEARTBEAT,
	NIOS2RES_SETTTY,
	NIOS2RES_SIGNAL,
	NIOS2RES_STDIN,
	NIOS2RES_TIMEOUT
} niosResCmd;

enum resNiosCmd {
	RES2NIOS_CONNECT,
	RES2NIOS_EOF,
	RES2NIOS_NEWTASK,
	RES2NIOS_REQUEUE,
	RES2NIOS_STATUS,
	RES2NIOS_STDERR,
	RES2NIOS_STDOUT
} resNiosCmd;